CHECKPOINT_DIR: "/snel/share/share/derived/selective_backprop/runs/ndt/sr04/"
DATA:
  DATAPATH: "/snel/share/share/derived/selective_backprop/runs/ndt/data/I152_R61_seed0_SR0.4"
  #DATAPATH: "/snel/share/share/derived/selective_backprop/runs/ndt/data/I152_R91_seed0_SR0.6"
  #DATAPATH: "/snel/share/share/derived/selective_backprop/runs/ndt/data/I152_R46_seed0_SR0.3"
  #DATAPATH: "/snel/share/share/derived/selective_backprop/runs/ndt/data/I152_R152_seed0_SR1.0"
  TRAIN_FILENAME: 'lfads_sparse_obs.h5'
  VAL_FILENAME: 'lfads_sparse_obs.h5'
MODEL:
  TRIAL_LENGTH: 70
  LEARNABLE_POSITION: True
  PRE_NORM: True
  FIXUP_INIT: True
  NUM_LAYERS: 2
  EMBED_DIM: 0
  LOGRATE: True
TRAIN:
  LR:
    WARMUP: 5000
  MASK_RATIO: 0.25
  WEIGHT_DECAY: 5.0e-05
  PATIENCE: 3000
  LOG_INTERVAL: 200
  VAL_INTERVAL: 20
  CHECKPOINT_INTERVAL: 1000
  NUM_UPDATES: 50501
  MASK_SPAN_RAMP_START: 8000
  MASK_SPAN_RAMP_END: 12000

  TUNE_HP_JSON: './configs/20ms_arxiv.json' # This space has more aggressive regularization
